#!/usr/bin/env python

import os
import sys
import getopt
import glob

import config
import dev_server
import generate

DEST_DIR = os.getcwd()

def create():
	os.mkdir(os.path.join(DEST_DIR, 'source'))
	os.mkdir(os.path.join(DEST_DIR, 'html'))
	os.mkdir(os.path.join(DEST_DIR, 'templates'))
	f = open(os.path.join(DEST_DIR, 'ssg.yaml'), "w")
	f.write("version: 1\n")
	f.write("template_dir: ./templates\n")
	f.write("output_dir: ./html\n")
	f.write("serve_dir: ./html\n")
	f.write("source_dir: ./source\n")
	f.close()

def usage():
	print "usage: ssg options"
	print "  where options are:"
	print "    -c[reate]   = creates a skeleton project in current directory"
	print "    -g[enerate] = generate the output"
	print "    -s[erve]    = serves HTML directory on localhost:9876"
	print "  when using the long forms prepend --"
	print "  example: ssg --create"

def main():
	try:
		opts, args = getopt.getopt(sys.argv[1:],
				"cgs",
				["create","generate","serve"])
	except getopt.GetoptError, err:
		print str(err)
		usage()
		sys.exit(2)
	for o, a in opts:
		if o in ("-c", "--create"):
			create()
		elif o in ("-g", "--generate"):
			generate.generate()
		elif o in ("-s", "--serve"):
			dev_server.serve()
	if len(opts) == 0:
		usage()

if __name__=="__main__":
    main()

