#!/usr/bin/env python

import os
import sys
import getopt

import config
import dev_server

DEST_DIR = os.getcwd()

def create():
	os.mkdir(os.path.join(DEST_DIR, 'source'))
	os.mkdir(os.path.join(DEST_DIR, 'html'))
	os.mkdir(os.path.join(DEST_DIR, 'templates'))
	f = open(os.path.join(DEST_DIR, 'ssg.yaml'), "w")
	f.write("version: 1\n")
	f.write("templates: ./templates\n")
	f.write("html: ./html\n")
	f.write("source: ./source\n")
	f.close()

def serve():
	from BaseHTTPServer import HTTPServer
	from BaseHTTPServer import BaseHTTPRequestHandler
	try:
		srv = HTTPServer(("", 9876), dev_server.SsgDevServer)
		print "Serving on localhost:9876"
		srv.serve_forever()
	except KeyboardInterrupt:
		srv.socket.close()

def usage():
	print "usage: ssg options"
	print "  where options are:"
	print "    -c[reate] = creates a skeleton project in current directory"
	print "    -s[erve]  = serves HTML directory on localhost:9876"
	print "  when using the long forms prepend --"
	print "  example: ssg --create"

def main():
	try:
		opts, args = getopt.getopt(sys.argv[1:],
				"cs",
				["create","serve"])
	except getopt.GetoptError, err:
		print str(err)
		usage()
		sys.exit(2)
	for o, a in opts:
		if o in ("-c", "--create"):
			create()
		elif o in ("-s", "--serve"):
			serve()
	if len(opts) == 0:
		usage()

if __name__=="__main__":
    main()

